name: CI

on: [push]

jobs:

  run-test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test
        run: npm install && npm test

  discord-notification:
    name: Discord notification
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: AvocaDev-Front
          color: '#00ff77'
          details: Test succeeded.
          webhookUrl: ${{ secrets.DISCORD_FRONT }}
