name: CD

on: [push]
  # push:
  #   branches:
  #     - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t ${{ secrets.DOCKER_IMAGE_REGISTRY }}:$(echo $GITHUB_SHA | head -c7)

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry
        run: docker push ${{ secrets.DOCKER_IMAGE_REGISTRY }}:$(echo $GITHUB_SHA | head -c7) 

      - name: Tag image
        run: docker tag  ${{ secrets.DOCKER_IMAGE_REGISTRY }}:$(echo $GITHUB_SHA | head -c7) ${{ secrets.DOCKER_IMAGE_REGISTRY }}:latest

        - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry
        run: docker push ${{ secrets.DOCKER_IMAGE_REGISTRY }}:latest


  run_new_app_containers:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_ElENA }}
        key: ${{ secrets.DROPLET_ELENA_KEY }}
          # docker tag ${{ secrets.DOCKER_IMAGE_REGISTRY }}:$(echo $GITHUB_SHA | head -c7) ${{ secrets.DOCKER_IMAGE_REGISTRY }}
        script: |
          cd ../nutriguide-project
          docker-compose down
          doctl registry login -t ${{ secrets.DIGITALOCEAN_TOKEN }}
          docker pull ${{ secrets.DOCKER_IMAGE_REGISTRY }}:$(echo $GITHUB_SHA | head -c7)
          docker-compose up -d
