name: CI

on: [push]

jobs:
  discord-notification:
    name: Run Test and Discord notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test
        run: npm install && npm test
      - uses: actions/checkout@master
      - name: Test success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          username: AvocaDev-Front
          color: '#00ff77'
          avatarUrl: https://ih1.redbubble.net/image.1174013826.2437/st,small,507x507-pad,600x600,f8f8f8.jpg
          details: Test succeeded.
          webhookUrl: ${{ secrets.DISCORD_FRONT }}
      - name: Test failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: AvocaDev-Front
          color: '#ff0000'
          avatarUrl: https://image.shutterstock.com/image-vector/funny-cute-avocado-character-vector-260nw-1667771986.jpg
          details: Test failed.
          webhookUrl: ${{ secrets.DISCORD_FRONT }}
